### ISSUE TITLE
Adjust CSS for list for widget in page/post content area

### ISSUE THREAD

**Issue by kharissulistiyo** [wcasia/2023-website#27]
It looks like the style for list of a widget (that appears in page/post content) hasn't yet been styled. For consistency, the CSS that has been added for [this issue](https://github.com/wcasia/2023-website/issues/5#event-6884717840) could be implemented.

Visit [this 404 page](https://asia.wordcamp.org/2023/sponsorshigggp-packages/) for direct checking.

![Screen Shot 2022-07-02 at 16 25 43](https://user-images.githubusercontent.com/1859092/176994819-6994aa1b-5523-4afb-9738-09820344d75e.png) 

![IMG_0800](https://user-images.githubusercontent.com/1859092/176994864-50347959-d725-462d-93d5-4881dfccc508.PNG)

**Comment by kharissulistiyo** [comment]
@nielslange yes, please assign this issue to me. Thanks you!

**Comment by nielslange** [comment]
It's your issue, @kharissulistiyo.

**Comment by kharissulistiyo** [comment]
Thank you @nielslange! 

I raised a new PR for this issue [here: #33](https://github.com/wcasia/2023-website/pull/33).
