### ISSUE TITLE
Delete the sample page 

### ISSUE THREAD

**Issue by kharissulistiyo** [wcasia/2023-website#34]
![Screen Shot 2022-07-07 at 08 34 14](https://user-images.githubusercontent.com/1859092/177671338-1630540d-6e7d-487b-89b3-57d3343e98aa.png)

It looks like [the Sample Page](https://asia.wordcamp.org/2023/sample-page/) was added from installation process of WordPress and currently remains public. Do we need to delete it? Please confirm, so I can assign this issue to myself and delete the page. Thanks!

**Comment by nielslange** [comment]
Good catch, @kharissulistiyo. You can delete the sample page and close this ticket then. 😀
